const ETFs=[
 {t:'CSPX',name:'S&P 500',region:'US',cap:'Large',target:65,pe:30.20,pb:5.55,trend:72,risk:67,macro:68,ter:.07,holdings:504,isin:'IE00B5BMR087',core:true,asof:'2026-07-20'},
 {t:'EIMI',name:'Emerging Markets IMI',region:'Emerging',cap:'All',target:20,pe:null,pb:null,trend:66,risk:55,macro:64,ter:.18,holdings:3057,isin:'IE00BKM4GZ66',core:true},
 {t:'WSML',name:'World Small Cap',region:'Developed',cap:'Small',target:15,pe:null,pb:null,trend:61,risk:53,macro:62,ter:.35,holdings:3562,isin:'IE00BF4RFH31',core:true},
 {t:'SSAC',name:'MSCI ACWI',region:'Global',cap:'Large/Mid',target:0,pe:null,pb:null,trend:68,risk:65,macro:67,ter:.20,holdings:1700,isin:'IE00B6R52259'},
 {t:'VWRA',name:'FTSE All-World',region:'Global',cap:'Large/Mid',target:0,pe:null,pb:null,trend:68,risk:65,macro:67,ter:.19,holdings:3780,isin:'IE00BK5BQT80'},
 {t:'SWDA',name:'MSCI World',region:'Developed',cap:'Large/Mid',target:0,pe:null,pb:null,trend:69,risk:66,macro:67,ter:.20,holdings:1300,isin:'IE00B4L5Y983'},
 {t:'VEVE',name:'FTSE Developed World',region:'Developed',cap:'Large/Mid',target:0,pe:null,pb:null,trend:68,risk:66,macro:67,ter:.12,holdings:2000,isin:'IE00BKX55T58'},
 {t:'VUAA',name:'S&P 500',region:'US',cap:'Large',target:0,pe:30.20,pb:5.55,trend:72,risk:67,macro:68,ter:.07,holdings:500,isin:'IE00BFMXXD54'},
 {t:'SPYL',name:'S&P 500',region:'US',cap:'Large',target:0,pe:30.20,pb:5.55,trend:72,risk:67,macro:68,ter:.03,holdings:500,isin:'IE000XZSV718'},
 {t:'IUS3',name:'MSCI Europe',region:'Europe',cap:'Large/Mid',target:0,pe:null,pb:null,trend:64,risk:64,macro:64,ter:.12,holdings:400,isin:'IE00B4K48X80'},
 {t:'CSP1',name:'S&P 500 (GBP listing)',region:'US',cap:'Large',target:0,pe:30.20,pb:5.55,trend:72,risk:67,macro:68,ter:.07,holdings:504,isin:'IE00B5BMR087'}
];
const $=s=>document.querySelector(s),holdings=$('#holdings'),signals=$('#signals');const saved=JSON.parse(localStorage.getItem('broadEtfV4')||localStorage.getItem('broadEtfV31')||'{}');
ETFs.filter(e=>e.core).forEach(e=>{holdings.insertAdjacentHTML('beforeend',`<div class='holdingrow'><label><b>${e.t}</b> — ${e.name}<small>${e.isin}</small></label><input class='holding' data-t='${e.t}' type='number' min='0' value='${saved[e.t]||0}'></div>`);signals.insertAdjacentHTML('beforeend',`<div class='signalrow'><b>${e.t}</b><label>P/E <input class='metric' data-t='${e.t}' data-k='pe' type='number' step='.01' min='0' value='${e.pe??''}' placeholder='N/A'></label><label>P/B <input class='metric' data-t='${e.t}' data-k='pb' type='number' step='.01' min='0' value='${e.pb??''}' placeholder='N/A'></label><label>Trend <input class='metric' data-t='${e.t}' data-k='trend' type='number' min='0' max='100' value='${e.trend}'></label></div>`);$('#priceTicker').insertAdjacentHTML('beforeend',`<option>${e.t}</option>`)});ETFs.forEach(e=>{let o=`<option value='${e.t}'>${e.t} — ${e.name}</option>`;$('#compareA').insertAdjacentHTML('beforeend',o);$('#compareB').insertAdjacentHTML('beforeend',o)});$('#compareB').selectedIndex=1;
function clamp(x,a=0,b=100){return Math.max(a,Math.min(b,x))}function label(s){return s>=80?['Strong Buy','buy']:s>=68?['Buy','buy']:s>=55?['Buy gradually','hold']:s>=42?['Hold / Wait','neutral']:['Wait','wait']}function fmt(x,n=2){return Number.isFinite(x)?x.toFixed(n):'N/A'}
function portfolio(){let vals={},total=0;document.querySelectorAll('.holding').forEach(x=>{vals[x.dataset.t]=+x.value||0;total+=+x.value||0});document.querySelectorAll('.metric').forEach(x=>{let e=ETFs.find(z=>z.t===x.dataset.t),v=x.value.trim();e[x.dataset.k]=v===''?null:+v});return{vals,total}}
function valuationScores(){let pes=ETFs.filter(e=>e.pe>0).map(e=>e.pe),pbs=ETFs.filter(e=>e.pb>0).map(e=>e.pb),minpe=Math.min(...pes),maxpe=Math.max(...pes),minpb=Math.min(...pbs),maxpb=Math.max(...pbs);ETFs.forEach(e=>{let parts=[];if(e.pe>0)parts.push(maxpe===minpe?50:100*(maxpe-e.pe)/(maxpe-minpe));if(e.pb>0)parts.push(maxpb===minpb?50:100*(maxpb-e.pb)/(maxpb-minpb));e.val=parts.length?Math.round(parts.reduce((a,b)=>a+b,0)/parts.length):50})}
function ret(p,n){if(p.length<=n)return null;return p[p.length-1]/p[p.length-1-n]-1}function std(a){if(a.length<2)return 0;let m=a.reduce((x,y)=>x+y,0)/a.length;return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}function calcPrices(p){let r=[];for(let i=1;i<p.length;i++)r.push(p[i]/p[i-1]-1);let periods=[[ret(p,20),15],[ret(p,60),25],[ret(p,120),25],[ret(p,250),25]],avail=periods.filter(x=>x[0]!=null),mom=avail.length?avail.reduce((s,x)=>s+clamp(50+x[0]*150)*x[1],0)/avail.reduce((s,x)=>s+x[1],0):50,max=Math.max(...p),dd=p[p.length-1]/max-1,vol=std(r)*Math.sqrt(252),trend=Math.round(.8*mom+.2*clamp(100+dd*250)),risk=Math.round(clamp(95-vol*140));return{trend,risk,vol,dd}}
function run(){let budget=+$('input#budget').value||0,{vals,total}=portfolio();valuationScores();let scored=ETFs.map(e=>{let current=e.core&&total?100*(vals[e.t]||0)/total:0,need=e.target?clamp(50+(e.target-current)*3,5,100):25,s=Math.round(.30*e.val+.25*(e.trend??50)+.20*need+.15*e.risk+.10*e.macro);return{...e,current,need,s}}),best=scored.filter(e=>e.core).sort((a,b)=>b.s-a.s)[0],q=label(best.s);$('#pick').textContent=`AED ${budget.toLocaleString()} → ${best.t}`;$('#score').textContent=best.s;$('#signal').innerHTML=`<span class='signal ${q[1]}'>${q[0]}</span>`;$('#reason').textContent=`${best.name} ranks highest among the target funds using the currently entered market data. ${total?`${best.t} is ${best.current.toFixed(1)}% of the core portfolio versus a ${best.target}% target.`:'Target weights prioritise a new portfolio.'}`;$('#why').innerHTML=`<span>Valuation ${best.val}/100</span><span>Trend ${best.trend??50}/100</span><span>Allocation need ${best.need.toFixed(0)}/100</span>`;let post=total+budget,after=post?((vals[best.t]||0)+budget)/post*100:0;$('#metrics').innerHTML=`<div><b>AED ${total.toLocaleString()}</b><small>Core portfolio entered</small></div><div><b>AED ${budget.toLocaleString()}</b><small>Next contribution</small></div><div><b>${after.toFixed(1)}%</b><small>${best.t} after contribution</small></div><div><b>${best.ter.toFixed(2)}%</b><small>${best.t} TER</small></div>`;let show=$('#alternatives').checked;$('#rows').innerHTML=scored.filter(e=>show||e.core).sort((a,b)=>b.s-a.s).map(e=>{let z=label(e.s);return `<tr><td><b>${e.t}</b><small>${e.isin}</small></td><td>${e.name}<small>${e.region} · ${e.cap} · ~${e.holdings.toLocaleString()} holdings</small></td><td>${e.target?e.target+'%':'Research'}</td><td>${e.core?e.current.toFixed(1)+'%':'—'}</td><td>${fmt(e.pe)}</td><td>${fmt(e.pb)}</td><td>${e.val}</td><td>${e.trend??'N/A'}</td><td>${e.risk}</td><td><b>${e.s}</b></td><td class='signal ${z[1]}'>${e.core?z[0]:'Research only'}</td></tr>`}).join('')}
function save(){let o={};document.querySelectorAll('.holding').forEach(x=>o[x.dataset.t]=+x.value||0);localStorage.setItem('broadEtfV4',JSON.stringify(o));run()}
function overlap(a,b){if(a.isin===b.isin)return 'Same underlying fund / different listing: effectively complete overlap.';if(a.name.startsWith('S&P 500')&&b.name.startsWith('S&P 500'))return 'Both track the S&P 500: effectively complete index overlap.';if(a.region==='Global'&&b.region==='Global')return 'High structural overlap: both are global large/mid-cap portfolios.';if((a.region==='US'&&b.region==='Global')||(b.region==='US'&&a.region==='Global'))return 'Meaningful overlap: global indices contain a large US allocation.';if((a.cap==='Small'&&b.cap==='Large/Mid')||(b.cap==='Small'&&a.cap==='Large/Mid'))return 'Lower direct market-cap overlap; exposures can complement each other.';return 'Some overlap may exist; holdings-level data is required for an exact percentage.'}
$('#compareBtn').onclick=()=>{let a=ETFs.find(e=>e.t===$('#compareA').value),b=ETFs.find(e=>e.t===$('#compareB').value);$('#compareResult').innerHTML=`<div class='tablewrap'><table><thead><tr><th></th><th>${a.t}</th><th>${b.t}</th></tr></thead><tbody><tr><td>Exposure</td><td>${a.name}</td><td>${b.name}</td></tr><tr><td>Region</td><td>${a.region}</td><td>${b.region}</td></tr><tr><td>TER</td><td>${a.ter.toFixed(2)}%</td><td>${b.ter.toFixed(2)}%</td></tr><tr><td>P/E</td><td>${fmt(a.pe)}</td><td>${fmt(b.pe)}</td></tr><tr><td>P/B</td><td>${fmt(a.pb)}</td><td>${fmt(b.pb)}</td></tr><tr><td>ISIN</td><td>${a.isin}</td><td>${b.isin}</td></tr></tbody></table></div><p><b>Overlap assessment:</b> ${overlap(a,b)}</p>`};
$('#calcSignal').onclick=()=>{let p=$('#priceHistory').value.split(/[\s,;]+/).map(Number).filter(x=>Number.isFinite(x)&&x>0);if(p.length<10){$('#calcResult').innerHTML='<span>Please provide at least 10 valid closing prices.</span>';return}let t=$('#priceTicker').value,e=ETFs.find(x=>x.t===t),m=calcPrices(p);e.trend=m.trend;e.risk=m.risk;document.querySelector(`.metric[data-t='${t}'][data-k='trend']`).value=m.trend;$('#calcResult').innerHTML=`<span><b>${t}</b> trend ${m.trend}/100</span><span>Risk ${m.risk}/100</span><span>Annualised volatility ${(m.vol*100).toFixed(1)}%</span><span>Drawdown ${(m.dd*100).toFixed(1)}%</span>`;run()};
$('#applyReference').onclick=()=>{$('#dataStatus').textContent='DATED REFERENCE';$('#asOf').textContent='CSPX issuer valuation snapshot: 20 July 2026. Other funds require updated issuer metrics; missing values remain neutral rather than guessed.';run()};$('#run').onclick=()=>{run();let p=$('#pick').textContent,s=$('#score').textContent,h=$('#history');if(h.classList.contains('muted')){h.classList.remove('muted');h.innerHTML=''}h.insertAdjacentHTML('afterbegin',`<p><b>${new Date().toLocaleString()}</b> — ${p} (${s}/100)</p>`)};$('#save').onclick=save;$('#reset').onclick=()=>{document.querySelectorAll('.holding').forEach(x=>x.value=0);['broadEtfV4','broadEtfV31','broadEtfV3'].forEach(k=>localStorage.removeItem(k));run()};$('#alternatives').onchange=run;$('#asOf').textContent='Reference market data is dated; verify freshness before acting.';run();