const ETFs=[
 {t:'CSPX',name:'S&P 500',target:65,val:48,trend:72,risk:67,macro:68,ter:.07,holdings:504,isin:'IE00B5BMR087'},
 {t:'EIMI',name:'Emerging Markets IMI',target:20,val:76,trend:66,risk:55,macro:64,ter:.18,holdings:3000,isin:'IE00BKM4GZ66'},
 {t:'WSML',name:'World Small Cap',target:15,val:70,trend:61,risk:53,macro:62,ter:.35,holdings:3500,isin:'IE00BF4RFH31'},
 {t:'SSAC',name:'MSCI ACWI',target:0,val:60,trend:68,risk:65,macro:67,ter:.20,holdings:1700,isin:'IE00B6R52259'},
 {t:'VWRA',name:'FTSE All-World',target:0,val:61,trend:68,risk:65,macro:67,ter:.19,holdings:3780,isin:'IE00BK5BQT80'}
];
const $=s=>document.querySelector(s), holdings=$('#holdings'), signals=$('#signals');
const saved=JSON.parse(localStorage.getItem('broadEtfV2')||'{}');
ETFs.forEach(e=>{holdings.insertAdjacentHTML('beforeend',`<div class='holdingrow'><label><b>${e.t}</b> — ${e.name}<small>${e.isin}</small></label><input class='holding' data-t='${e.t}' type='number' min='0' value='${saved[e.t]||0}'></div>`);signals.insertAdjacentHTML('beforeend',`<div class='signalrow'><b>${e.t}</b><label>Valuation <input class='market' data-t='${e.t}' data-k='val' type='number' min='0' max='100' value='${e.val}'></label><label>Trend <input class='market' data-t='${e.t}' data-k='trend' type='number' min='0' max='100' value='${e.trend}'></label></div>`)});
function label(s){return s>=80?['Strong Buy','buy']:s>=68?['Buy','buy']:s>=55?['Buy gradually','hold']:s>=42?['Hold / Wait','neutral']:['Wait','wait']}
function data(){let vals={},total=0;document.querySelectorAll('.holding').forEach(x=>{vals[x.dataset.t]=+x.value||0;total+=+x.value||0});document.querySelectorAll('.market').forEach(x=>{let e=ETFs.find(z=>z.t===x.dataset.t);e[x.dataset.k]=Math.max(0,Math.min(100,+x.value||0))});return{vals,total}}
function run(){let budget=+$('input#budget').value||0,{vals,total}=data();let scored=ETFs.map(e=>{let current=total?100*(vals[e.t]||0)/total:0;let gap=e.target-current;let need=e.target?Math.max(5,Math.min(100,50+gap*3)):25;let s=Math.round(.30*e.val+.25*e.trend+.20*need+.15*e.risk+.10*e.macro);return{...e,current,gap,need,s}});let eligible=scored.filter(e=>e.target>0).sort((a,b)=>b.s-a.s),best=eligible[0],q=label(best.s);$('#pick').textContent=`AED ${budget.toLocaleString()} → ${best.t}`;$('#score').textContent=best.s;$('#signal').innerHTML=`<span class='signal ${q[1]}'>${q[0]}</span>`;let allocationText=total?`${best.t} is ${best.current.toFixed(1)}% of the entered portfolio versus a ${best.target}% target.`:`This is a new portfolio; target weights are used to prioritise the first contributions.`;$('#reason').textContent=`${best.name} currently ranks highest for the next contribution. ${allocationText}`;$('#why').innerHTML=`<span>Valuation ${best.val}/100</span><span>Trend ${best.trend}/100</span><span>Allocation need ${best.need.toFixed(0)}/100</span>`;
let invested=total,post=invested+budget;$('#metrics').innerHTML=`<div><b>AED ${invested.toLocaleString()}</b><small>Portfolio entered</small></div><div><b>AED ${budget.toLocaleString()}</b><small>Next contribution</small></div><div><b>${post?((vals[best.t]||0)+budget)/post*100:0 .toFixed?.(1)}%</b><small>${best.t} after contribution</small></div><div><b>${best.ter.toFixed(2)}%</b><small>${best.t} TER</small></div>`;
let showAlt=$('#alternatives').checked;$('#rows').innerHTML=scored.filter(e=>showAlt||e.target>0).map(e=>{let z=label(e.s);return `<tr><td><b>${e.t}</b><small>${e.isin}</small></td><td>${e.name}<small>~${e.holdings.toLocaleString()} holdings</small></td><td>${e.target?e.target+'%':'Alternative'}</td><td>${e.current.toFixed(1)}%</td><td>${e.val}</td><td>${e.trend}</td><td>${e.risk}</td><td>${e.need.toFixed(0)}</td><td><b>${e.s}</b></td><td class='signal ${z[1]}'>${z[0]}</td></tr>`}).join('');}
function save(){let o={};document.querySelectorAll('.holding').forEach(x=>o[x.dataset.t]=+x.value||0);localStorage.setItem('broadEtfV2',JSON.stringify(o));run()}
$('#run').onclick=()=>{run();let b=+$('input#budget').value||0,p=$('#pick').textContent,s=$('#score').textContent,h=$('#history');if(h.classList.contains('muted')){h.classList.remove('muted');h.innerHTML=''}h.insertAdjacentHTML('afterbegin',`<p><b>${new Date().toLocaleString()}</b> — ${p} (${s}/100)</p>`)};$('#save').onclick=save;$('#reset').onclick=()=>{document.querySelectorAll('.holding').forEach(x=>x.value=0);localStorage.removeItem('broadEtfV2');run()};$('#alternatives').onchange=run;run();