// V17 — resilient same-origin market cache adapter
// Replaces fragile browser-to-third-party market requests with a validated cache
// generated by GitHub Actions. Preserves last-known-good local data on failures.
(()=>{
  const CORE=['CSPX','EIMI','WSML'];
  const STORE='broadEtfHistories';
  const MIN=200;
  const DAY=86400000;
  const el=id=>document.getElementById(id);
  const getLocal=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return{}}};
  const validRows=rows=>Array.isArray(rows)&&rows.length>=MIN&&rows.every(r=>r&&r.d&&Number.isFinite(Number(r.p))&&Number(r.p)>0);
  const stateFor=date=>{const age=Math.floor((Date.now()-new Date(date+'T23:59:59Z').getTime())/DAY);return age<=4?'FRESH CACHE':age<=10?'CACHED':'STALE CACHE'};
  function render(status,source,details){
    if(el('feedStatus'))el('feedStatus').textContent=status;
    if(el('refreshResult'))el('refreshResult').innerHTML=`<span><b>${status}</b> — ${source}</span>${details.map(x=>`<span>${x}</span>`).join('')}`;
  }
  function mirrorForValidation(ticker,rows,source){
    try{localStorage.setItem(`priceHistory_${ticker}`,JSON.stringify({ticker,source,loadedAt:new Date().toISOString(),rows:rows.map(r=>({date:r.d,close:Number(r.p)}))}))}catch{}
  }
  async function refresh(){
    const button=el('refreshMarket'); if(button)button.disabled=true;
    if(el('feedStatus'))el('feedStatus').textContent='REFRESHING';
    try{
      const response=await fetch(`data/market-history.json?t=${Date.now()}`,{cache:'no-store'});
      if(!response.ok)throw new Error(`cache HTTP ${response.status}`);
      const payload=await response.json();
      const next={...getLocal()},details=[];
      for(const ticker of CORE){
        const item=payload?.symbols?.[ticker];
        if(!item||!validRows(item.rows))throw new Error(`${ticker}: validated cache unavailable`);
        next[ticker]=item.rows.map(r=>({d:r.d,p:Number(r.p)}));
        mirrorForValidation(ticker,next[ticker],payload.source||'validated same-origin cache');
        details.push(`${ticker}: ${next[ticker].length} closes · latest ${item.latestDate||next[ticker].at(-1).d}`);
      }
      localStorage.setItem(STORE,JSON.stringify(next));
      const latest=CORE.map(t=>payload.symbols[t].latestDate||payload.symbols[t].rows.at(-1).d).sort().at(0);
      const status=stateFor(latest);
      render(status,`${payload.source||'Validated same-origin cache'} · generated ${payload.generatedAt?new Date(payload.generatedAt).toLocaleString():'unknown time'}`,details);
      window.dispatchEvent(new CustomEvent('broad-etf-market-updated',{detail:{status,source:payload.source}}));
      window.BroadEtfValidation?.render?.(); window.BroadEtfAllocationAudit?.render?.();
      return true;
    }catch(error){
      const local=getLocal();
      const usable=CORE.every(t=>validRows(local[t]));
      if(usable){
        CORE.forEach(t=>mirrorForValidation(t,local[t],'last-known-good local cache'));
        render('CACHED LOCAL','Live cache refresh unavailable. Retaining previously validated local history.',CORE.map(t=>`${t}: ${local[t].length} stored closes`));
      }else{
        render('UNAVAILABLE','No recommendation-grade market history is currently available.',[String(error.message||error),'Market timing remains blocked; portfolio allocation tools remain usable.']);
      }
      window.BroadEtfValidation?.render?.();
      return false;
    }finally{if(button)button.disabled=false}
  }
  function bind(){
    const button=el('refreshMarket');if(!button)return;
    // Capture phase prevents older experimental handlers from making blocked third-party requests.
    button.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();refresh();},true);
    window.BroadEtfMarketCache={refresh,getLocal};
    refresh();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
