(()=>{
const KEY='etfMonthlyReviewsV11';
const core=['CSPX','EIMI','WSML'];
const money=n=>`AED ${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0})}`;
const num=v=>{const n=parseFloat(v);return Number.isFinite(n)?n:null};
function latestAudit(){try{return (JSON.parse(localStorage.getItem('etfRecommendationAuditV101')||'[]')||[])[0]||null}catch(e){return null}}
function priorReviews(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')||[]}catch(e){return []}}
function holdings(){const out={};core.forEach(t=>out[t]=num(document.querySelector(`[data-holding="${t}"]`)?.value)||0);return out}
function snapshot(t){try{const raw=localStorage.getItem(`etfPriceHistory_${t}`)||localStorage.getItem(`priceHistory_${t}`);const x=JSON.parse(raw||'null');if(!x)return null;const arr=Array.isArray(x)?x:(x.prices||x.data||[]);if(!arr.length)return null;const last=arr[arr.length-1];return typeof last==='number'?{price:last,date:null}:{price:num(last.close??last.price??last.value),date:last.date||last.Date||null}}catch(e){return null}}
function render(){const box=document.getElementById('monthlyReview');if(!box)return;const reviews=priorReviews();if(!reviews.length){box.innerHTML='<p class="muted">No monthly reviews yet. Refresh market data, run this month’s decision, then save a review.</p>';return}box.innerHTML=`<div class="tablewrap"><table><thead><tr><th>Month</th><th>Recommendation</th><th>Contribution</th><th>Score</th><th>Confidence</th><th>Portfolio</th></tr></thead><tbody>${reviews.slice(0,12).map(r=>`<tr><td>${r.month}</td><td><b>${r.pick||'—'}</b></td><td>${money(r.contribution)}</td><td>${r.score??'—'}</td><td>${r.confidence||'—'}</td><td>${core.map(t=>`${t} ${money(r.holdings?.[t])}`).join('<br>')}</td></tr>`).join('')}</tbody></table></div>`}
function save(){const audit=latestAudit();const pick=document.getElementById('pick')?.textContent?.trim();const score=document.getElementById('score')?.textContent?.trim();const contribution=num(document.getElementById('budget')?.value)||0;const confidence=document.getElementById('dataStatus')?.textContent?.trim()||audit?.confidence||'Unknown';const now=new Date();const rec={id:now.toISOString(),month:now.toLocaleDateString(undefined,{year:'numeric',month:'short'}),pick:pick&&pick!=='—'?pick:(audit?.pick||'—'),score:score&&score!=='—'?score:(audit?.score??'—'),confidence,contribution,holdings:holdings(),prices:Object.fromEntries(core.map(t=>[t,snapshot(t)])),reason:document.getElementById('reason')?.textContent?.trim()||''};let reviews=priorReviews();reviews=reviews.filter(r=>r.month!==rec.month);reviews.unshift(rec);localStorage.setItem(KEY,JSON.stringify(reviews.slice(0,36)));render();document.getElementById('reviewStatus').textContent=`Saved ${rec.month} review. Next month, the dashboard can compare allocation and recommendation changes against this snapshot.`}
function drift(){const h=holdings(),total=core.reduce((s,t)=>s+h[t],0);const targets={CSPX:.65,EIMI:.20,WSML:.15};const el=document.getElementById('monthlyDrift');if(!el)return;if(!total){el.innerHTML='<span>Enter portfolio values to calculate allocation drift.</span>';return}const rows=core.map(t=>{const w=h[t]/total,d=w-targets[t];return {t,w,d}});const most=rows.slice().sort((a,b)=>a.d-b.d)[0];el.innerHTML=rows.map(x=>`<span>${x.t}: ${(x.w*100).toFixed(1)}% vs ${(targets[x.t]*100).toFixed(0)}% target (${x.d>=0?'+':''}${(x.d*100).toFixed(1)}pp)</span>`).join('')+`<span><b>Largest underweight:</b> ${most.t}</span>`}
window.addEventListener('DOMContentLoaded',()=>{render();drift();document.getElementById('saveMonthlyReview')?.addEventListener('click',save);document.getElementById('clearMonthlyReviews')?.addEventListener('click',()=>{localStorage.removeItem(KEY);render();document.getElementById('reviewStatus').textContent='Monthly review history cleared.'});document.getElementById('save')?.addEventListener('click',()=>setTimeout(drift,50));document.getElementById('run')?.addEventListener('click',()=>setTimeout(drift,100));});
})();